# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_auto_20180414_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstar',
            name='cate_id',
        ),
        migrations.RemoveField(
            model_name='userstar',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u5206\u7c7b', 'verbose_name_plural': '\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237'},
        ),
        migrations.AlterModelOptions(
            name='userlogininfo',
            options={'verbose_name': '\u7528\u6237\u767b\u5f55\u4fe1\u606f\u8868', 'verbose_name_plural': '\u7528\u6237\u767b\u5f55\u4fe1\u606f\u8868'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='cate_id',
        ),
        migrations.RemoveField(
            model_name='userlogininfo',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='cate',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='email_verify',
            field=models.IntegerField(choices=[(0, b'\xe6\x9c\xaa\xe9\xaa\x8c\xe8\xaf\x81'), (1, b'\xe5\xb7\xb2\xe9\xaa\x8c\xe8\xaf\x81')], default=0, verbose_name=b'Email\xe6\x98\xaf\xe5\x90\xa6\xe5\xb7\xb2\xe7\xbb\x8f\xe9\xaa\x8c\xe8\xaf\x81'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_validate',
            field=models.IntegerField(choices=[(0, b'\xe6\x9c\xaa\xe9\xaa\x8c\xe8\xaf\x81'), (1, b'\xe5\xb7\xb2\xe9\xaa\x8c\xe8\xaf\x81')], default=0, verbose_name='\u59d3\u540d\u662f\u5426\u9a8c\u8bc1'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='mobile_verify',
            field=models.IntegerField(choices=[(0, b'\xe6\x9c\xaa\xe9\xaa\x8c\xe8\xaf\x81'), (1, b'\xe5\xb7\xb2\xe9\xaa\x8c\xe8\xaf\x81')], default=0, verbose_name=b'Mobile\xe6\x98\xaf\xe5\x90\xa6\xe5\xb7\xb2\xe7\xbb\x8f\xe9\xaa\x8c\xe8\xaf\x81'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='pwd',
            field=models.CharField(default=b'', max_length=20, verbose_name=''),
        ),
        migrations.AddField(
            model_name='newuser',
            name='session',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe7\x99\xbb\xe5\xbd\x95\xe6\x97\xb6\xe4\xbc\x9a\xe5\x86\x99\xe5\x85\xa5\xe5\xbd\x93\xe5\x89\x8dsession_key'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='truename',
            field=models.CharField(default=b'', max_length=20, verbose_name='\u771f\u5b9e\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6240\u5728\u5730'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='img',
            field=models.ImageField(blank=True, default=b'', upload_to=b'imgs/img_user', verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f'),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='login_time',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xb8\x80\xe6\xac\xa1\xe7\x99\xbb\xe5\xbd\x95\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserStar',
        ),
    ]
