# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_auto_20180414_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_service', models.IntegerField(default=1, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe6\x80\x81\xe5\xba\xa6')),
                ('star_personal', models.IntegerField(default=1, verbose_name=b'\xe4\xb8\x93\xe4\xb8\x9a\xe7\xa8\x8b\xe5\xba\xa6')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u661f\u7ea7\u8868',
                'verbose_name_plural': '\u7528\u6237\u661f\u7ea7\u8868',
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cate',
            new_name='cate_id',
        ),
        migrations.AddField(
            model_name='userstar',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focus.Category'),
        ),
        migrations.AddField(
            model_name='userstar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
