# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_auto_20180414_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('contact_date', models.DateTimeField(auto_now=True, verbose_name=b'\xe9\x82\x80\xe8\xaf\xb7\xe6\x97\xb6\xe9\x97\xb4')),
                ('task_date', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xbb\xbb\xe5\x8a\xa1\xe6\x97\xb6\xe9\x97\xb4')),
                ('contact_type', models.IntegerField(default=0)),
                ('cate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='focus.Category', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u9080\u8bf7\u8868',
                'verbose_name_plural': '\u7528\u6237\u9080\u8bf7\u8868',
            },
        ),
    ]
