# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_remark', models.IntegerField(default=0, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0\xe9\x87\x8f')),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now=True, verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe6\x97\xb6\xe9\x97\xb4')),
                ('state', models.IntegerField(default=1, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\xb1\x95\xe7\x8e\xb0')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8bc4\u4ef7\u8868',
                'verbose_name_plural': '\u8ba2\u5355\u8bc4\u4ef7\u8868',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactremark',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='focus.Contact'),
        ),
        migrations.AddField(
            model_name='contactremark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
