# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_auto_20180414_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_following', models.IntegerField(choices=[(-1, b'None'), (0, b'False'), (1, b'True')], default=-1, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6Following')),
                ('is_block', models.IntegerField(choices=[(-1, b'None'), (0, b'False'), (1, b'True')], default=-1, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6Block')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x85\xb3\xe6\xb3\xa8\xe9\x82\xa3\xe4\xb8\xaa\xe7\x94\xa8\xe6\x88\xb7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7684Following \u548c Block \u5173\u7cfb\u8868',
                'verbose_name_plural': '\u7528\u6237\u7684Following \u548c Block \u5173\u7cfb\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=set([('user', 'following')]),
        ),
    ]
