# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0008_auto_20180414_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogininfo',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.IntegerField(choices=[((b'0', b'nouse'), (b'1', b'inuse'))], default=1, verbose_name=b'\xe7\xb1\xbb\xe5\x88\xab\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.DeleteModel(
            name='UserLoginInfo',
        ),
    ]
