# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0009_auto_20180414_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='pcate_id',
            new_name='pcate',
        ),
    ]
