# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0010_auto_20180414_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='pcate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focus.Category'),
        ),
    ]
