# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0012_auto_20180414_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstar',
            name='desc',
            field=models.CharField(default=b'', max_length=300, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x86\x85\xe8\xa1\x8c\xe8\xa1\x8c\xe4\xb8\x9a\xe8\x87\xaa\xe6\x88\x91\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
    ]
