# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_pref',
            field=models.BooleanField(default=False, help_text='\u662f\u5426\u662f\u5185\u884c\u4eba'),
        ),
    ]
