# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_type', models.IntegerField(choices=[(0, 'unknown'), (1, 'qq'), (2, 'wechat'), (3, 'taobao'), (4, 'skype'), (5, 'linkin'), (6, '\u672a\u77e5')], default=0, verbose_name='\u5f00\u653e\u5e10\u53f7\u7c7b\u578b')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5f00\u653e\u767b\u5f55\u5e10\u53f7\u8868',
                'verbose_name_plural': '\u7528\u6237\u5f00\u653e\u767b\u5f55\u5e10\u53f7\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserValidateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_type', models.IntegerField(choices=[(0, '\u8eab\u4efd\u8bc1'), (1, '\u62a4\u7167'), (2, '\u5b66\u751f\u8bc1'), (3, '\u5de5\u4f5c\u8bc1'), (4, '\u58eb\u5175\u8bc1'), (5, '\u624b\u673a\u53f7'), (6, '\u90ae\u7bb1'), (7, '\u672a\u77e5')], default=0, verbose_name='\u8ba4\u8bc1\u7c7b\u578b')),
                ('cert_no', models.CharField(default='', max_length=50, verbose_name='\u8ba4\u8bc1\u53f7\u7801')),
                ('valid_state', models.IntegerField(choices=[(0, '\u672a\u8ba4\u8bc1'), (1, '\u8ba4\u8bc1\u4e2d'), (2, '\u5df2\u8ba4\u8bc1'), (3, '\u672a\u77e5'), (4, '\u58eb\u5175\u8bc1'), (5, '\u624b\u673a\u53f7'), (6, '\u90ae\u7bb1')], default=0, verbose_name='\u8ba4\u8bc1\u72b6\u6001')),
                ('valid_captcha', models.CharField(default='', max_length=15, verbose_name='\u8ba4\u8bc1\u9a8c\u8bc1\u7801')),
                ('valid_captcha_exp', models.CharField(default='', max_length=25, verbose_name='\u8ba4\u8bc1\u9a8c\u8bc1\u7801\u8fc7\u671f\u65f6\u95f4')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='\u7533\u8bf7\u9a8c\u8bc1\u65f6\u95f4')),
                ('audit_time', models.DateTimeField(auto_now=True, verbose_name='\u5ba1\u6838\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8eab\u4efd\u8ba4\u8bc1\u8d44\u6599\u8868',
                'verbose_name_plural': '\u7528\u6237\u8eab\u4efd\u8ba4\u8bc1\u8d44\u6599\u8868',
            },
        ),
    ]
