# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_is_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
