# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180422_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, '\u672a\u7b7e\u5230'), (True, '\u5df2\u7ecf\u7b7e\u5230')], verbose_name='\u662f\u5426\u7b7e\u5230')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='\u7b7e\u5230\u65e5\u671f')),
                ('signed_day', models.IntegerField(default=0, verbose_name='\u8fde\u7eed\u7b7e\u5230\u5929\u6570')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7b7e\u5230',
                'verbose_name_plural': '\u7528\u6237\u7b7e\u5230',
            },
        ),
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='\u6dfb\u52a0\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='\u4e2a\u4eba\u7b80\u4ecb'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='my_home',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='\u767b\u5f55\u540e\u9996\u9875\u8df3\u8f6c'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(blank=True, default='/static/img/default-avatar.png', upload_to='imgs/img_user', verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='uservalidateinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='signedinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='signedinfo',
            unique_together=set([('user', 'signed_day')]),
        ),
    ]
