# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180524_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedinfo',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='\u7b7e\u5230\u65e5\u671f'),
        ),
    ]
