# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderremark',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderremark_buyer', to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u5bb6'),
        ),
        migrations.AddField(
            model_name='orderremark',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Category'),
        ),
        migrations.AddField(
            model_name='orderremark',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='orderremark',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderremark_seller', to=settings.AUTH_USER_MODEL, verbose_name='\u5356\u5bb6'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Address', verbose_name='\u6536\u8d27\u5730\u5740\u8868'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='cate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Logistics', verbose_name='\u7269\u6d41'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_buyer', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u8d27\u4eba\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_seller', to=settings.AUTH_USER_MODEL, verbose_name='\u5546\u5bb6'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
