# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_phone', models.CharField(max_length=20, verbose_name='\u6536\u8d27\u4eba\u8054\u7cfb\u7535\u8bdd')),
                ('buyer_phone_bak', models.CharField(max_length=20, verbose_name='\u5907\u7528\u8054\u7cfb\u7535\u8bdd')),
                ('seller_phone', models.CharField(max_length=20, verbose_name='\u6536\u8d27\u4eba\u8054\u7cfb\u7535\u8bdd')),
                ('seller_phone_bak', models.CharField(max_length=20, verbose_name='\u5907\u7528\u8054\u7cfb\u7535\u8bdd')),
                ('address', models.CharField(max_length=50, verbose_name='\u6536\u8d27\u5730\u5740')),
                ('zipcode', models.CharField(max_length=15, verbose_name='\u90ae\u653f\u7f16\u7801')),
                ('desc', models.CharField(max_length=150, verbose_name='\u63cf\u8ff0')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u8d27\u4eba\u59d3\u540d')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='\u5546\u5bb6')),
            ],
        ),
    ]
