# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_remark', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570\u91cf')),
                ('content', models.CharField(max_length=300, verbose_name='\u8bc4\u4ef7\u5185\u5bb9')),
                ('score_service', models.IntegerField(default=3, verbose_name='\u670d\u52a1\u6001\u5ea6')),
                ('score_personal', models.IntegerField(default=3, verbose_name='\u4e13\u4e1a\u7a0b\u5ea6')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u4ef7\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u8bc4\u4ef7\u65f6\u95f4')),
                ('state', models.IntegerField(default=1, verbose_name='\u662f\u5426\u5c55\u73b0')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderremark_buyer', to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u5bb6')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Category')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderremark_seller', to=settings.AUTH_USER_MODEL, verbose_name='\u5356\u5bb6')),
            ],
        ),
        migrations.AddField(
            model_name='logistics',
            name='express_type',
            field=models.IntegerField(choices=[(0, 'ems'), (1, 'epress'), (2, 'other'), (3, 'none')], default=3, verbose_name='\u7269\u6d41\u65b9\u5f0f'),
        ),
    ]
