# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 04:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180418_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_buyer', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u8d27\u4eba\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_seller', to=settings.AUTH_USER_MODEL, verbose_name='\u5546\u5bb6'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Address', verbose_name='\u6536\u8d27\u5730\u5740\u8868'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Logistics', verbose_name='\u7269\u6d41'),
        ),
    ]
